language: node_js

os:
  - linux
  - osx

node_js:
  - 6
cache:
  directories:
    - "node_modules"

before_install:
  - npm i -g yarn@latest

install:
  - yarn install

script:
  - yarn test

sudo: false
